[DRAFT] Writing workshop
EdenComp/Workshop-React-TS pull request #1
Opened 2022-06-13 08:40 UTC by EdenComp

# Description

This PR is the writing part of the workshop, including [README](./README.md) for workshop exercises and [SETUP](./SETUP.md) for installation instructions.

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [ ] I have assigned this PR to myself
- [ ] I have added at least 1 reviewer
- [ ] I have added the needed labels
- [ ] I have linked this PR to an issue
- [ ] I have linked this PR to a milestone
- [ ] I have linked this PR to a project
- [ ] I have tested this code
- [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

2022-06-26 17:13 UTC, RezaRahemtola requested changes
Lot of small details to change, also try to format the steps like this https://github.com/PoCInnovation/Workshops/tree/master/software/18.Kafka
with Description/Tasks/Documentation (Validation if needed but useless for this workshop imo)

2022-06-26 17:13 UTC, RezaRahemtola commented on README.md
> +The goal of this workshop is to create a [Kanban-like](https://www.digite.com/kanban/what-is-kanban/) application using the React library in Typescript
Not really a Kanban-like app anymore :joy:

2022-06-26 17:13 UTC, RezaRahemtola commented on README.md
> +`Components` are the core of React. They represent a single element in a web page, like a `text` box, a `button`, a `div` etc. All combined together, they create a fully working web page. These compo
add some official documentation links, like https://reactjs.org/docs/components-and-props.html here for example

2022-06-26 17:13 UTC, RezaRahemtola commented on README.md
> +In Typescript, we must specify the type of the return value of the function: for all TSX React components, you can use `React.Element`.
JSX.Element

2022-06-26 17:13 UTC, RezaRahemtola commented on README.md
> +function Title(): React.Element {
Same for the type

2022-06-26 17:13 UTC, RezaRahemtola commented on README.md
> +Now that you know how to create a component in React, let's get into Material UI.
same, add a link to Material UI's website

2022-06-26 17:13 UTC, RezaRahemtola commented on README.md
> +The goal of this task is to create the `Task` component: this component will represent a task with all its information, including:
The goal of this **step** may be better to avoid repeating Task

2022-06-26 17:13 UTC, RezaRahemtola commented on README.md
> +> From now, we recommend you to create a `Components` folder in your `src` folder, and to create one file per component and naming it with the name of your component. For instance, the `Task` compone
isn't this an old version ? Already did this comment too for the capitalized `Components` -> it should be `components`

2022-06-26 17:13 UTC, RezaRahemtola commented on README.md
> +You can then use [React Props](https://reactjs.org/docs/components-and-props.html) to pass variables from your main components to your children components, and iterate your `Tasks array` with the Jav
if you talk specifically about props, maybe add a link precisely about it (another one or an anchor on this page like https://reactjs.org/docs/components-and-props.html#rendering-a-component)

2022-06-26 17:13 UTC, RezaRahemtola commented on README.md
> +From now, you are able to create static components that doesn't interact with the user.
don't instead of doesn't

2022-06-26 17:13 UTC, RezaRahemtola commented on README.md
> +We will now create dynamic components to allow the user to create a new task to the list, using [React hooks](https://reactjs.org/docs/hooks-intro.html).
`to add a new task to the list` looks better.

`create [..] to the list` is strange :joy:

2022-06-26 17:13 UTC, RezaRahemtola commented on README.md
> +- You can link your application to a `backend` and a `database` to properly store your tasks (EPyTodo ?)
add some links in the bonus part, like some backend frameworks compatible with React (Next, Remix...)

2022-06-26 17:17 UTC, EdenComp commented on README.md
> +The goal of this workshop is to create a [Kanban-like](https://www.digite.com/kanban/what-is-kanban/) application using the React library in Typescript
Still a kanban - At least todo list aiming to create a kanban

2022-06-26 17:19 UTC, EdenComp commented on README.md
> +`Components` are the core of React. They represent a single element in a web page, like a `text` box, a `button`, a `div` etc. All combined together, they create a fully working web page. These compo
Done

2022-06-28 08:56 UTC, RezaRahemtola approved these changes
LGTM

2022-06-28 13:13 UTC, merged